YosysHQ/prjtrellis

fuzzers/020-tap_drive/fuzzer.py
fuzzers/020-tap_drive/tap.ncl
fuzzers/021-spine/fuzzer.py
fuzzers/021-spine/spine_45k.ncl
fuzzers/030-cib_routing/cibroute.ncl
fuzzers/030-cib_routing/fuzzer.py
libtrellis/CMakeLists.txt
libtrellis/examples/config_all.py
libtrellis/include/Chip.hpp
libtrellis/src/Chip.cpp
libtrellis/src/PyTrellis.cpp
tools/html_all.py
tools/html_bits.py
util/common/isptcl.py
util/common/nets.py
util/fuzz/interconnect.py

At the moment this PR contains fuzzers for:
- TAP_DRIVE and TAP_DRIVE_CIB row clock control tiles
- CIB tiles (interconnect to top and bottom IO)
- SPINE tiles for the 45k tiles only (some 25k and 85k SPINE tiles missing)

Adding fuzzers for some global clock tiles and CIBs

---

libtrellis/CMakeLists.txt
libtrellis/src/PyTrellis.cpp
libtrellis/tools/ecppack.cpp
libtrellis/tools/ecpunpack.cpp

-Made building python module optional
-Made creation of shared library optional
-Made creating static build an option
-Created ability to specify Trellis database location from command lines
Aim is to make possible creation of additional Apio support for ECP5 using these tools

Static build

---

libtrellis/CMakeLists.txt

This is based on code from LLVM and so it should be quite portable.

cmake: Use RPATH for libtrellis binaries

---

misc/openocd/ecp5-versa.cfg
misc/openocd/ecp5-versa5g.cfg

Should be 8 according to datasheet.
This is still not uncommented because `svf -tap ecp5.tap` does not
seem to work for me.

misc: Fix ecp5-versa{,5g} ispclock.tap -irlen parameter

---

devices.json
libtrellis/include/Chip.hpp
libtrellis/include/Tile.hpp
libtrellis/src/Chip.cpp
libtrellis/src/Database.cpp
libtrellis/src/PyTrellis.cpp
libtrellis/src/Tile.cpp
tools/connectivity.py
tools/demobuilder/design.py
tools/demobuilder/route.py
tools/html_tilegrid.py
util/common/nets.py
util/common/tiles.py
util/fuzz/interconnect.py

Within Project Trellis, there were no less than 3 separate functions for obtaining a location of a tile from its name. This PR refactors Project Trellis, particularly the Python utility functions, so that all code uses a single function to map a Tile name to a location (`Trellis::get_row_col_pair_from_chipsize`, also exported to `pytrellis`).

Refactor out duplicate "tile name to location mapping".

---

libtrellis/tools/ecppack.cpp

This brings the IDCODE commandline in line with other tools, such as openocd config TAP IDs etc.

libtrellis: Allow hex in IDCODE override in ecppack

---

libtrellis/src/BitDatabase.cpp

When an unsupported I/O voltage or mode is set on a pin, it triggers a std::out_of_range exception in EnumSettingBits::set_value, which doesn't give a nice error message. This prints out the failing key and  range of options stored in the map, making debugging a little easier.

Add a more descriptive error for std::out_of_range in map::at 

---

libtrellis/include/Bitstream.hpp
libtrellis/src/Bitstream.cpp
libtrellis/tools/ecppack.cpp

During read from SPI Flash, once this command is reached,
the device will switch to specified mode.
Available modes:
* Read (default)
* Fast Read
* Dual SPI Read
* Quad SPI Read
This is harder to test consistently, but it appears to mostly work.
Signed-off-by: Jens Andersen <jens.andersen@gmail.com>

libtrellis: Allow specifying spimode for ecppack

---

libtrellis/CMakeLists.txt

https://github.com/SymbiFlow/prjtrellis/commit/1283bb1385acbbdc83326d71d8df0f4a7f49972e broke the installation on OS X as no lib64 exists on OS X.
This PR fixes this and additionally moves the binary libraries to the lib/lib64 folders instead of the trellis subfolder so that it can be found automatically e.g. by cmake's find_library.
Follow-up pull request for nextpnr will follow.

Fix libraries on OS X

---

libtrellis/tools/ecppll.cpp

This is an update to @emard's pr #63 to use std::string in place of const char*, fix a memory corruption issue in the way the pll struct was being used, and unify the named/unnamed clock generation.

ecppll: named signals

---

examples/picorv32_ulx3s/Makefile

Currently this fails with:
nextpnr-ecp5 --45k --package CABGA381 --json attosoc.json --textcfg attosoc_out.config --45k --no-tmdriv
option '--45k' cannot be specified more than once
Remove redundant option.
Signed-off-by: Michael Neuling <mikey@neuling.org>

Remove redundant --45k option from picorv32_ulx3s Makefile

---

fuzzers/ECP5/067-ioreg/fuzzer.py
fuzzers/ECP5/067-ioreg/iologic.ncl
libtrellis/src/Bels.cpp
libtrellis/src/Chip.cpp
minitests/iologic/iddr7.v
minitests/iologic/oreg.v
minitests/iologic/toreg.v

- Add ECLKBRIDGECS and associated BRGECLKSYNC bels to libtrellis
- Add the SLIP pin to the IOLOGIC Bel, needed for 7:1 input mode
- Add missing config bits related to IO registers

IOLOGIC improvements

---

examples/ecp5_evn/Makefile
examples/picorv32_versa5g/Makefile
examples/soc_ecp5_evn/Makefile
examples/soc_versa5g/Makefile
examples/versa5g/Makefile

By default, make prog uses $(TRELLIS) to provides the openocd config file path.
This variable is hardcoded to /usr/share/trellis, so if libtrellis is installed in other location (/usr/local is the cmake default path) openocd fails with:
embedded:startup.tcl:60: Error: Can't find /usr/share/trellis/misc/openocd/ecp5-evn.cfg
By replacing = by ?=, it's now possible to use:
TRELLIS=/usr/local/share/trellis make prog

examples: allows to override TRELLIS when libtrellis is not installed in /usr

---

diamond.sh

Long overdue, but I cherry-picked some useful changes from my custom `diamond.sh`:
* `DIAMONDVER`: Allows the user to override the Diamond toolchain version they have installed. If not set, it defaults to `3.10`.
* `JEDEC_BITSTREAM`: Allows the user to generate a JEDEC bitstream for easy programming if necessary. We discussed this a while ago (June 2019); only _now_ was I in a position to implement it.
This is a stopgap PR to make merging my changes to `diamond.sh` easier; I'll make a PR for the remaining changes soon.

Add DIAMONDVER and JEDEC_BITSTREAM env variables.

---

examples/ulx3s/Makefile

Use installed binary (of ecppll) in $PATH,
not the leftover from the build inside the repo with relative path

Fix Makefile of example

---

docs/architecture/bitstream_format.rst

This commit fixes the following warnings:
```
symbiflow-docs/source/prjtrellis/docs/architecture/bitstream_format.rst:110: WARNING: Block quote ends without a blank line; unexpected unindent.   
symbiflow-docs/source/prjtrellis/docs/architecture/bitstream_format.rst:145: WARNING: Unexpected indentation. 
```

Fix wrong indentation warnings in documentation

---

README.md

for "_Ensure to include the ECP5 architecture when building nextpnr_" in the docs

include example ECP5 architecture syntax

---

libtrellis/CMakeLists.txt

BUILD_PYTHON determines if python support will be included.
install target have pytrellis even if BUILD_PYTHON is not set.
This commit fix that.

pytrellis should be target if BUILD_PYTHON exists

---

libtrellis/.gitignore
libtrellis/include/Tile.hpp
libtrellis/src/Bitstream.cpp
libtrellis/src/Tile.cpp
tools/connectivity.py
tools/demobuilder/design.py
tools/demobuilder/route.py
tools/extract_tilegrid.py
tools/get_tilegrid_all.py
tools/html_all.py
tools/html_tilegrid.py
util/common/isptcl.py
util/common/nets.py
util/fuzz/dbfixup.py
util/fuzz/interconnect.py

This is two commits... commit e078b48 deals with adding column bias and Windows support to Python files under `tools` and `utils`.
Subsequent commit brings in my changes to libtrellis for dealing with MachXO2's "wonderful" tile-naming scheme, column biasing conversion, as well as bitstream generation (the `BitstreamOptions` class).
While nothing should have broken, _I have not tested the bitstream generation changes on ECP5 (and have no boards to test on). Please make sure nothing breaks before committing._

Refactor util tools

---

devices.json

Actually a 25k chip with a different IDCODE, fixes #55 and other hacks in existence around the internet.

Add '12k' device

---

libtrellis/tools/ecpbram.cpp

Verify any addresses given for consistency: raise an error if the
specified address isn't what we expected, or silently continue if
it's the address we would have used anyway.
Signed-off-by: Gary Wong <gtw@gnu.org>

ecpbram: Handle Verilog hex file @address syntax.

---

.github/archlinux/PKGBUILD
.github/workflows/arch-pkg.yml

Example run: https://travis-ci.com/github/FFY00/prjtrellis/builds/160309099
When https://github.com/SymbiFlow/sphinxcontrib-markdown-symlinks/issues/8 gets sorted we can start building the documentation in the package.
Before merging this I think it would make sense to consider using Github Actions instead. Github Actions allows us to reuse actions (example: https://github.com/JamesIves/github-pages-deploy-action, see it in action: https://github.com/libratbag/ratbag-emu/blob/master/.github/workflows/docpush.yml). This would allow us to maintain a separate repo with the package building and artifact deployment logic and then only define the build scripts in the different repos. Github Actions is free and unlimited for open-source, and allows us to host our own runners if needed (travis …

github: build archlinux package

---

libtrellis/src/RoutingGraph.cpp

Per IRC messages, we both agree `belsUphill` and `belsDownhill` are reversed from intended. Functionally, this PR shouldn't change anything- other than fixing an [assertion](https://github.com/SymbiFlow/prjtrellis/blob/master/libtrellis/src/DedupChipdb.cpp#L107) because `belsUphill` and `belsDownhill` ultimately become part of the [same](https://github.com/SymbiFlow/prjtrellis/blob/master/libtrellis/src/DedupChipdb.cpp#L101-L113) `vector` during deduplication. `nextpnr` therefore never knows that these data structures were reversed!
However, it's best to correct this for documentation purposes :).
Please make sure to test this PR against generated blobs to make sure nothing breaks. As far as I can tell, these are in fact the only lines that need to be changed.

Reverse belsUphill and belsDownhill assignments- agreed to be typo.

---

libtrellis/tools/ecppack.cpp

I'm in the process of creating a [Verilog Build System](https://github.com/gojimmypi/msbuildCustomTask/blob/development/VerilogBuild/VerilogBuild.csproj) for Visual Studio as part of my [Verilog Language Extension](https://marketplace.visualstudio.com/items?itemName=gojimmypi.gojimmypi-verilog-language-extension) as inspired by @BarryNolte in his [Project Template for Verilog #25](https://github.com/gojimmypi/VerilogLanguageExtension/pull/25)
I'd like to have this `--version` capability for all external commands used so that better diagnostics can be implemented in the [project file](https://github.com/gojimmypi/msbuildCustomTask/blob/428abadc950b74d2b4801e017009c56282a368ee/VerilogBuild/VerilogBuild.csproj#L527)  similar to that available for `yosys` and `nextpnr`.

Add --version commandline option for ecppack

---

libtrellis/tools/ecppll.cpp

Unlike other tools, `ecppll --help` returns with exit code 1. This PR makes it consistent with others by replacing `return 1;` with `return vm.count("help") ? 0 : 1;`.

ecppll: return from '--help' with exit code 0

---

fuzzers/machxo2/102-oscg/fuzzer.py
libtrellis/src/PyTrellis.cpp
libtrellis/src/RoutingGraph.cpp

This PR fixes some routing graph oversights, making sure that the left-right tiles in MachXO2 and the STDBY pin of the internal oscillator are properly connected to the routing graph. A more general solution may be required for all MachXO2 parts, but this will be fine for `LCMXO2-1200HC` for now.

MachXO2 Support: Part 3

---

libtrellis/tools/ecpbram.cpp

On cross compile environment filename is in always in lower case.

Fix windows cross-compile

---

libtrellis/tools/ecppll.cpp

This is the regression introduced by commit b2884bf: CLKOP and CLKFB parameters should not be named as clkout0_name.
P.S. Tested when generating the reference frequency for the UART (256 * 115200 Hz) from system clock (25 MHz). The board used is Colorlight i5 v7.0 with Muse Lab development board.

ecppll: fix broken port names in highres mode, fix regression

---

libtrellis/tools/ecppll.cpp

I forgot to do this in the previous commit.

ecppll: declare internal feedback wire explicitly in highres mode

---

diamond.sh
diamond_tcl.sh

If the user manually specifies `LM_LICENSE_FILE` (maybe because the license file is in a non-standard location), use the specified location instead of the hardcoded location.

allow user specified LM_LICENSE_FILE

---

libtrellis/src/PyTrellis.cpp

This adds some obviously missing constructors to the pytrellis mappings.
These were found by searching for all occurrences of `pytrellis[^()]*\(.*\)`, but there might be still some more missing.
None of the fuzzers had time to run through for me yet, but I think these changes should be uncontroversial..

add some missing constructors to pytrellis

---

tools/ecp_vlog.py

In the spirit of [`icebox_vlog.py`](https://github.com/YosysHQ/icestorm/blob/master/icebox/icebox_vlog.py), this commit adds an `ecp_vlog.py` script which converts a bitstream into a Verilog file.
This was used successfully to solve the challenge "Ethernet from above" at Pwn2Win 2021, and was tested with the bitfile from that challenge. I do not guarantee that every edge case has been handled: additional testcases welcome.
This version only contains stub EBR support, because EBR support was not necessary to get the target design to work. It also contains a bunch of very finicky workarounds for some harder edge cases - feedback on better approaches to solve the edge cases (such as FX/OFX/Fn confusion in CCU2 mode) would be helpful. However, it should be useful for the general case of a …

Add a tool for automatic bitstream -> Verilog conversion

---

libtrellis/src/PyTrellis.cpp

Found one more missing pytrellis binding, now atleast `001-plc2_routing` and `051-pio_ioconfig` run through successfully.

add missing pytrellis `add` binding to ConfigBitSet

---

README.md

According to my (quick) research /usr/local is for stuff manually compiled, so we rather should install there. This (/usr/local) is also the path mentionned in the compiling-instructions for nextpnr. I might be wrong however and the Readme of nextpnr needs to be updated, feel free to reject this PR in this case. Anyway something is not consistent at the moment and it creates problems like here: https://github.com/YosysHQ/nextpnr/issues/781

Readme: Install to /usr/local instead of /usr (?)

---

libtrellis/CMakeLists.txt

If git isn't present, don't try to cache the build configuration.

Fix building without git

---

libtrellis/include/Chip.hpp
libtrellis/include/DedupChipdb.hpp
libtrellis/include/RoutingGraph.hpp
libtrellis/src/Chip.cpp
libtrellis/src/DedupChipdb.cpp
libtrellis/src/PyTrellis.cpp

This adds the pseudo-pips to the database necessary for LUT permutation

libtrellis: LUT permutation support for ECP5

---

examples/ecp5_evn/Makefile
examples/ecp5_evn_multiboot/Makefile
examples/tinyfpga_ax/Makefile
examples/tinyfpga_rev1/Makefile
examples/tinyfpga_rev2/Makefile
examples/ulx3s/Makefile
examples/ulx3s_12k_multiboot/Makefile
examples/versa5g/Makefile

In some Makefiles, the PHONY target was missing or not consistent
with the actual targets in the Makefile.
Thanks!

examples/Makefiles: fix PHONY targets

---

.github/workflows/arch-pkg.yml

Switch to use v1 tag instead of relying on master branch (which has been dropped in favor of main).

Fix arch package building workflow

---

libtrellis/CMakeLists.txt

These are not required as of wasi-sdk-19 and Boost 1.81.

CMake: prune no longer necessary Boost definitions

---

libtrellis/tools/wasmexcept.hpp

- Quash warnings about unused parameters.
- Make [[noreturn]] functions actually not return.

Fix several issues with wasmexcept.hpp

---

libtrellis/src/Tile.cpp

This clk_col data was in center_map before rework, so this was left out. Anyway this fixes html view of MachXO and after this is merged new documentation can be generated

Fix MachXO locations

---

libtrellis/CMakeLists.txt

This is explicitly recommended by the FindPython module documentation
and is required to avoid failed builds on some systems. See:
https://cmake.org/cmake/help/latest/module/FindPython.html

Find all components of Python at the same time

---

libtrellis/tools/ecpmulti.cpp

`ecpmulti` allows users to store multiple bitstreams in the same `bin`/`mcs` files. By pressing `PROGRAMN`, the next bitstream is loaded in a specific order.
However, the jump table is missing, meaning the golden bitstream is not automatically used if the primary bitstream is corrupted.
The code to generate the jump table already exists but was never added at `flashsize & 0xff`.
This PR adds the missing jump table, enabling behavior similar to Lattice's `ddtcmd`. It also adds two new arguments:
- `--golden` to pass golden bitstream file name
- `--goldenaddr` to pass golden bitstream address.
**Notes:**
- according to **FPGA-TN-02203-1.8**:
- first bitstream is placed at offset `0x00`,
- second bitstream is the golden bitstream and placed at a address depending on the target FPGA
- …

libtrellis/tools/ecpmulti.cpp: Added the dual-boot/multi-boot jump table just before the end of the SPI flash
